language: node_js

node_js:
  - 0.10

before_install: npm conf set strict-ssl false
before_script: npm run-script lint
script: npm run-script lint

notifications:
  email:
    - tomaz+travisci@tomaz.me
